version: "3"
services:
  # client:
  #   container_name: client_vue
  #   build: ./client
  #   ports:
  #     - "8080:8080" # ホスト側のポート:コンテナ側のポート
  #   volumes:
  #     - ./client:/client # srcディレクトリのみマッピング
  #   tty: true
  server:
    container_name: server_go
    build: ./server # ビルド時のDockerfileの位置
    ports:
      - "3000:3000"
    volumes:
      - ./server:/go/src/server # マウントするディレクトリの指定
    tty: true # コンテナの永続化